import crypto from "node:crypto"
import fs from "node:fs/promises"
import os from "node:os"
import path from "node:path"
import { ipcMain } from "electron"
import { applyMigrations, openDatabase } from "@electron/database/db-core"
import { ensureWorkspace } from "@electron/others/workspace"

const selectSkill = `SELECT id, title, source, summary, updated_at as updatedAt FROM skills`
const starterFiles = JSON.stringify([{ path: "SKILL.md", content: "---\nname: \"New skill\"\ndescription: \"Describe what this skill does.\"\n---\n", language: "md", kind: "file" }])
export function registerSkillIpc() {
  ipcMain.handle("skills:list", async () => { const db = await database(); return db.prepare(`${selectSkill} ORDER BY updated_at DESC`).all() })
  ipcMain.handle("skills:listExternal", async () => { const results: Array<{ id: string; title: string; source: string; summary: string }> = []; for (const source of ["codex", "claude", "agents"]) { const directory = path.join(os.homedir(), `.${source}`, "skills"); try { for (const entry of await fs.readdir(directory, { withFileTypes: true })) if (entry.isDirectory()) results.push({ id: `${source}:${entry.name}`, title: entry.name, source, summary: path.join(directory, entry.name) }) } catch { /* optional external directory */ } } return results })
  ipcMain.handle("skills:get", async (_event, id: string) => { const db = await database(); return { skill: db.prepare(`${selectSkill} WHERE id = ?`).get(id) ?? null, versions: db.prepare(`SELECT id, major, minor, is_release as isRelease, created_at as createdAt, files_json as filesJson FROM skill_versions WHERE skill_id = ? ORDER BY major DESC, minor DESC, created_at DESC`).all(id) } })
  ipcMain.handle("skills:create", async () => { const db = await database(); const id = crypto.randomUUID(); const now = Date.now(); db.prepare(`INSERT INTO skills (id, title, source, summary, updated_at) VALUES (?, ?, ?, ?, ?)`).run(id, "New skill", "custom", "", now); db.prepare(`INSERT INTO skill_versions (id, skill_id, major, minor, is_release, files_json, created_at) VALUES (?, ?, 1, 0, 0, ?, ?)`).run(crypto.randomUUID(), id, starterFiles, now); return getSkill(db, id) })
  ipcMain.handle("skills:save", async (_event, payload: { id: string; title: string; source: string; summary: string; filesJson: string; selectedVersionId?: string; publish?: boolean }) => { const db = await database(); const now = Date.now(); db.prepare(`UPDATE skills SET title = ?, source = ?, summary = ?, updated_at = ? WHERE id = ?`).run(payload.title, payload.source, payload.summary, now, payload.id); const draft = payload.selectedVersionId ? db.prepare(`SELECT id, is_release as isRelease FROM skill_versions WHERE skill_id = ? AND id = ?`).get(payload.id, payload.selectedVersionId) as { id: string; isRelease: number } | undefined : undefined; const selected = draft && !draft.isRelease ? draft.id : undefined; if (!payload.publish && selected) db.prepare(`UPDATE skill_versions SET files_json = ?, created_at = ? WHERE id = ?`).run(payload.filesJson, now, selected); else { const latest = db.prepare(`SELECT major, minor, is_release as isRelease FROM skill_versions WHERE skill_id = ? ORDER BY major DESC, minor DESC, created_at DESC LIMIT 1`).get(payload.id) as { major: number; minor: number; isRelease: number } | undefined; db.prepare(`INSERT INTO skill_versions (id, skill_id, major, minor, is_release, files_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(crypto.randomUUID(), payload.id, !latest ? 1 : latest.isRelease ? latest.major + 1 : latest.major, !latest || latest.isRelease ? 0 : latest.minor + 1, payload.publish ? 1 : 0, payload.filesJson, now) } return getSkill(db, payload.id) })
  ipcMain.handle("skills:delete", async (_event, id: string) => { const db = await database(); db.prepare(`DELETE FROM skill_versions WHERE skill_id = ?`).run(id); db.prepare(`DELETE FROM skills WHERE id = ?`).run(id); return { success: true } })
}
function getSkill(db: ReturnType<typeof openDatabase>, id: string) { return { skill: db.prepare(`${selectSkill} WHERE id = ?`).get(id), versions: db.prepare(`SELECT id, major, minor, is_release as isRelease, created_at as createdAt, files_json as filesJson FROM skill_versions WHERE skill_id = ? ORDER BY major DESC, minor DESC, created_at DESC`).all(id) } }
async function database() { await ensureWorkspace(); const db = openDatabase(); applyMigrations(db); return db }
