import { describe, expect, it } from 'vitest'
import type { AgentPipeline } from '@/types'
import {
  PIPELINE_EXPORT_SCHEMA_VERSION,
  PipelineImportError,
  buildPipelineExport,
  parsePipelineImport,
  serializePipelineExport,
} from './pipelinePortability'

const samplePipeline: AgentPipeline = {
  id: 'pipeline-1',
  name: 'Sample',
  description: 'Round-trip me',
  steps: [
    {
      agentId: 'agent-1',
      task: 'Draft {{vars.topic}}',
      retryCount: 1,
      retryBackoffMs: 250,
      retryBackoffStrategy: 'exponential',
    },
    {
      agentId: 'agent-2',
      task: 'Review {{previous.output}}',
      runIf: "previous.status == 'success'",
    },
  ],
  variables: [
    { name: 'topic', defaultValue: 'launch plan' },
  ],
  budget: {
    maxTotalDurationMs: 60_000,
    maxTotalTokens: 8000,
  },
  createdAt: 1000,
  updatedAt: 2000,
}

describe('pipelinePortability', () => {
  it('exports a portable envelope without runtime-specific fields', () => {
    const envelope = buildPipelineExport(samplePipeline)

    expect(envelope.schemaVersion).toBe(PIPELINE_EXPORT_SCHEMA_VERSION)
    expect(envelope.exportedBy).toBe('suora')
    expect(envelope.pipeline.name).toBe('Sample')
    expect(envelope.pipeline.steps).toHaveLength(2)
    expect((envelope.pipeline as unknown as Record<string, unknown>).id).toBeUndefined()
    expect((envelope.pipeline as unknown as Record<string, unknown>).createdAt).toBeUndefined()
  })

  it('round-trips serialize → parse preserving steps, variables, and budget', () => {
    const json = serializePipelineExport(samplePipeline)
    const { pipeline, warnings } = parsePipelineImport(json)

    expect(warnings).toEqual([])
    expect(pipeline.id).not.toBe(samplePipeline.id) // regenerated by default
    expect(pipeline.createdAt).not.toBe(samplePipeline.createdAt)
    expect(pipeline.name).toBe('Sample')
    expect(pipeline.steps).toEqual(samplePipeline.steps)
    expect(pipeline.variables).toEqual(samplePipeline.variables)
    expect(pipeline.budget).toEqual(samplePipeline.budget)
  })

  it('accepts a bare pipeline object as well as a wrapped envelope', () => {
    const bare = JSON.stringify({
      name: 'Bare',
      steps: [{ agentId: 'a', task: 'do it' }],
    })

    const { pipeline } = parsePipelineImport(bare)
    expect(pipeline.name).toBe('Bare')
    expect(pipeline.steps).toEqual([{ agentId: 'a', task: 'do it' }])
  })

  it('rejects payloads without a name or steps', () => {
    expect(() => parsePipelineImport('{}')).toThrow(PipelineImportError)
    expect(() => parsePipelineImport(JSON.stringify({ name: 'No steps' }))).toThrow(PipelineImportError)
    expect(() => parsePipelineImport('not json')).toThrow(PipelineImportError)
  })

  it('warns about a future schema version but still imports the pipeline', () => {
    const payload = JSON.stringify({
      schemaVersion: PIPELINE_EXPORT_SCHEMA_VERSION + 1,
      exportedAt: 0,
      exportedBy: 'suora',
      pipeline: { name: 'Future', steps: [{ agentId: 'a', task: 'do it' }] },
    })

    const { pipeline, warnings } = parsePipelineImport(payload)
    expect(pipeline.name).toBe('Future')
    expect(warnings.some((warning) => warning.includes('schema'))).toBe(true)
  })

  it('drops malformed budget values with a warning', () => {
    const payload = JSON.stringify({
      name: 'Bad budget',
      steps: [{ agentId: 'a', task: 'do it' }],
      budget: { maxTotalTokens: -1, maxStepCount: 'lots' },
    })

    const { pipeline, warnings } = parsePipelineImport(payload)
    expect(pipeline.budget).toBeUndefined()
    expect(warnings.length).toBeGreaterThan(0)
  })

  it('honors the optional name override', () => {
    const json = serializePipelineExport(samplePipeline)
    const { pipeline } = parsePipelineImport(json, { name: 'Renamed copy' })
    expect(pipeline.name).toBe('Renamed copy')
  })
})
