export const loadChatLayout = () => import('@/components/chat/ChatLayout')
export const loadDocumentsLayout = () => import('@/components/documents/DocumentsLayout')
export const loadPipelineLayout = () => import('@/components/pipeline/PipelineLayout')
export const loadModelsLayout = () => import('@/components/models/ModelsLayout')
export const loadAgentsLayout = () => import('@/components/agents/AgentsLayout')
export const loadSkillsLayout = () => import('@/components/skills/SkillsLayout')
export const loadTimerLayout = () => import('@/components/timer/TimerLayout')
export const loadChannelLayout = () => import('@/components/channels/ChannelLayout')
export const loadIntegrationsLayout = () => import('@/components/integrations/IntegrationsLayout')
export const loadSettingsLayout = () => import('@/components/settings/SettingsLayout')

export function preloadRoute(path: string): Promise<unknown> {
  if (path.startsWith('/chat')) return loadChatLayout()
  if (path.startsWith('/documents')) return loadDocumentsLayout()
  if (path.startsWith('/pipeline')) return loadPipelineLayout()
  if (path.startsWith('/models')) return loadModelsLayout()
  if (path.startsWith('/agents')) return loadAgentsLayout()
  if (path.startsWith('/skills')) return loadSkillsLayout()
  if (path.startsWith('/timer')) return loadTimerLayout()
  if (path.startsWith('/channels')) return loadChannelLayout()
  if (path.startsWith('/mcp')) return loadIntegrationsLayout()
  if (path.startsWith('/settings')) return loadSettingsLayout()
  return Promise.resolve()
}
