import crypto from "node:crypto"
import type { ChannelConfigRecord } from "@/data/domain/models"
import { httpRequest } from "@electron/others/channels/channel-runtime-http"
import { WECHAT_PERSONAL_API_TIMEOUT_MS, WECHAT_PERSONAL_APP_ID, WECHAT_PERSONAL_CLIENT_VERSION, WECHAT_PERSONAL_DEFAULT_BASE_URL, WECHAT_PERSONAL_LONG_POLL_TIMEOUT_MS, WECHAT_PERSONAL_QR_BOT_TYPE, type WeChatPersonalQrCodeResponse, type WeChatPersonalQrStatusResponse, type WeChatPersonalUpdatesResponse } from "@electron/others/channels/wechat-personal-types"

export function isValidWeChatPersonalToken(token: string) { return token.length > 0 && token.length <= 4096 && !/[\r\n]/.test(token) }
export function getWeChatPersonalBaseUrl(channel: ChannelConfigRecord) { return channel.wechatPersonalBaseUrl?.trim() || WECHAT_PERSONAL_DEFAULT_BASE_URL }
export function normalizeWeChatPersonalQrCodeUrl(value?: string) { const trimmed = value?.trim(); if (!trimmed) return undefined; return /^(?:data:|https?:\/\/|blob:|file:)/i.test(trimmed) ? trimmed : `data:image/png;base64,${trimmed}` }
function headers(token?: string) { const randomUin = crypto.randomBytes(4).readUInt32BE(0); return { "Content-Type": "application/json", AuthorizationType: "ilink_bot_token", "iLink-App-Id": WECHAT_PERSONAL_APP_ID, "iLink-App-ClientVersion": WECHAT_PERSONAL_CLIENT_VERSION, "X-WECHAT-UIN": Buffer.from(String(randomUin)).toString("base64"), ...(token?.trim() ? { Authorization: `Bearer ${token.trim()}` } : {}) } }
async function requestJson<T>(baseUrl: string, endpoint: string, method: "GET" | "POST", body?: Record<string, unknown>, options: { token?: string; timeoutMs?: number; query?: Record<string, string>; signal?: AbortSignal } = {}) { const url = new URL(endpoint, baseUrl.endsWith("/") ? baseUrl : `${baseUrl}/`); for (const [key, value] of Object.entries(options.query || {})) url.searchParams.set(key, value); const response = await httpRequest(url.toString(), { method, headers: headers(options.token), body: method === "POST" ? JSON.stringify(body) : undefined, timeoutMs: options.timeoutMs, signal: options.signal }); if (response.status < 200 || response.status >= 300) throw new Error(`HTTP ${response.status}: ${response.text}`); return response.data as T }
export function fetchWeChatPersonalQrCode(localTokenList: string[]) { return requestJson<WeChatPersonalQrCodeResponse>(WECHAT_PERSONAL_DEFAULT_BASE_URL, "ilink/bot/get_bot_qrcode", "POST", { local_token_list: localTokenList }, { query: { bot_type: WECHAT_PERSONAL_QR_BOT_TYPE }, timeoutMs: WECHAT_PERSONAL_API_TIMEOUT_MS }) }
export async function pollWeChatPersonalQrStatus(baseUrl: string, qrcode: string, verifyCode?: string) { const endpoint = `ilink/bot/get_qrcode_status?qrcode=${encodeURIComponent(qrcode)}${verifyCode?.trim() ? `&verify_code=${encodeURIComponent(verifyCode.trim())}` : ""}`; try { const response = await requestJson<WeChatPersonalQrStatusResponse>(baseUrl, endpoint, "GET", undefined, { timeoutMs: WECHAT_PERSONAL_LONG_POLL_TIMEOUT_MS }); return response.status ? { ...response, diagnosticEvent: "response", diagnosticMessage: `Upstream QR status: ${response.status}`, diagnosticBaseUrl: baseUrl, diagnosticEndpoint: endpoint } : { ...response, status: "wait" as const, diagnosticEvent: "invalid_response" as const, diagnosticMessage: "QR status response did not include a status field.", diagnosticBaseUrl: baseUrl, diagnosticEndpoint: endpoint } } catch (error) { return { status: "wait" as const, diagnosticEvent: error instanceof Error && error.name === "AbortError" ? "timeout" as const : "error" as const, diagnosticMessage: error instanceof Error ? error.message : String(error), diagnosticBaseUrl: baseUrl, diagnosticEndpoint: endpoint } } }
export function fetchWeChatPersonalUpdates(channel: ChannelConfigRecord, cursor: string, signal?: AbortSignal) { return requestJson<WeChatPersonalUpdatesResponse>(getWeChatPersonalBaseUrl(channel), "ilink/bot/getupdates", "POST", { get_updates_buf: cursor, base_info: { channel_version: "suora", bot_agent: "Suora" } }, { token: channel.wechatPersonalBotToken, timeoutMs: WECHAT_PERSONAL_LONG_POLL_TIMEOUT_MS, signal }) }
export async function sendWeChatPersonalNativeMessage(channel: ChannelConfigRecord, chatId: string, content: string, contextToken?: string) { if (!channel.wechatPersonalBotToken) return { success: false, error: "Missing personal WeChat bot token" }; try { await requestJson(getWeChatPersonalBaseUrl(channel), "ilink/bot/sendmessage", "POST", { msg: { from_user_id: "", to_user_id: chatId, client_id: `suora-wechat-${crypto.randomUUID()}`, message_type: 2, message_state: 2, item_list: [{ type: 1, text_item: { text: content } }], ...(contextToken ? { context_token: contextToken } : {}) } }, { token: channel.wechatPersonalBotToken }); return { success: true } } catch (error) { return { success: false, error: error instanceof Error ? error.message : String(error) } } }
