import crypto from "node:crypto"
import { ipcMain } from "electron"
import { applyMigrations, openDatabase } from "@electron/database/db-core"
import { ensureWorkspace } from "@electron/others/workspace"

const selectDocument = `SELECT id, title, summary, enabled, updated_at as updatedAt FROM documents`
const selectVersions = `SELECT id, major, minor, is_release as isRelease, created_at as createdAt, structure_json as structureJson, graph_json as graphJson, settings_json as settingsJson FROM document_versions`
export function registerDocumentIpc() {
  ipcMain.handle("documents:list", async () => { const database = await getDatabase(); return database.prepare(`${selectDocument} ORDER BY updated_at DESC`).all() })
  ipcMain.handle("documents:get", async (_event, id: string, versionId?: string) => { const database = await getDatabase(); const versions = database.prepare(`${selectVersions} WHERE document_id = ? ORDER BY major DESC, minor DESC, created_at DESC`).all(id); return { document: database.prepare(`${selectDocument} WHERE id = ?`).get(id) ?? null, versions, selectedVersionId: (versions as Array<{ id: string }>).find((version) => version.id === versionId)?.id ?? (versions as Array<{ id: string }>)[0]?.id ?? null } })
  ipcMain.handle("documents:create", async () => { const database = await getDatabase(); const id = crypto.randomUUID(); const versionId = crypto.randomUUID(); const folderId = crypto.randomUUID(); const now = Date.now(); const pages = [{ id: folderId, title: "guides", content: "", type: "folder", parentId: null }, { id: crypto.randomUUID(), title: "overview.md", content: "# New document\n\n## Overview\n\nStart writing here.\n", type: "document", parentId: folderId }]; database.prepare(`INSERT INTO documents (id, title, summary, enabled, updated_at) VALUES (?, ?, ?, ?, ?)`).run(id, "New document", "", 1, now); database.prepare(`INSERT INTO document_versions (id, document_id, major, minor, is_release, structure_json, graph_json, settings_json, created_at) VALUES (?, ?, 1, 0, 0, ?, ?, ?, ?)`).run(versionId, id, JSON.stringify({ pages }), JSON.stringify({ edges: [] }), JSON.stringify({ isPublic: false, includeInLlmsTxt: true }), now); return { document: database.prepare(`${selectDocument} WHERE id = ?`).get(id), versions: database.prepare(`${selectVersions} WHERE document_id = ?`).all(id), selectedVersionId: versionId } })
  ipcMain.handle("documents:save", async (_event, payload: { id: string; title: string; summary: string; enabled: boolean; structureJson: string; graphJson: string; settingsJson: string; selectedVersionId?: string; publish?: boolean }) => { const database = await getDatabase(); const now = Date.now(); database.prepare(`UPDATE documents SET title = ?, summary = ?, enabled = ?, updated_at = ? WHERE id = ?`).run(payload.title, payload.summary, payload.enabled ? 1 : 0, now, payload.id); const draft = payload.selectedVersionId ? database.prepare(`SELECT id, is_release as isRelease FROM document_versions WHERE document_id = ? AND id = ?`).get(payload.id, payload.selectedVersionId) as { id: string; isRelease: number } | undefined : undefined; const selected = draft && !draft.isRelease ? draft.id : (database.prepare(`SELECT id FROM document_versions WHERE document_id = ? AND is_release = 0 ORDER BY major DESC, minor DESC, created_at DESC LIMIT 1`).get(payload.id) as { id: string } | undefined)?.id; let selectedVersionId = selected; if (!payload.publish && selected) database.prepare(`UPDATE document_versions SET structure_json = ?, graph_json = ?, settings_json = ?, created_at = ? WHERE id = ?`).run(payload.structureJson, payload.graphJson, payload.settingsJson, now, selected); else { const latest = database.prepare(`SELECT major, minor, is_release as isRelease FROM document_versions WHERE document_id = ? ORDER BY major DESC, minor DESC, created_at DESC LIMIT 1`).get(payload.id) as { major: number; minor: number; isRelease: number } | undefined; selectedVersionId = crypto.randomUUID(); database.prepare(`INSERT INTO document_versions (id, document_id, major, minor, is_release, structure_json, graph_json, settings_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)`).run(selectedVersionId, payload.id, !latest ? 1 : latest.isRelease ? latest.major + 1 : latest.major, !latest || latest.isRelease ? 0 : latest.minor + 1, payload.publish ? 1 : 0, payload.structureJson, payload.graphJson, payload.settingsJson, now) } return { document: database.prepare(`${selectDocument} WHERE id = ?`).get(payload.id), versions: database.prepare(`${selectVersions} WHERE document_id = ?`).all(payload.id), selectedVersionId } })
  ipcMain.handle("documents:delete", async (_event, id: string) => { const database = await getDatabase(); database.prepare(`DELETE FROM document_versions WHERE document_id = ?`).run(id); database.prepare(`DELETE FROM documents WHERE id = ?`).run(id); return { success: true } })
}
async function getDatabase() { await ensureWorkspace(); const database = openDatabase(); applyMigrations(database); return database }
