import { createModel } from "@/electron/app/models/providers/model"
import type { ProviderPreset } from "@/types/agent"

export const bailianProvider: ProviderPreset = {
  providerType: "bailian",
  title: "Bailian",
  description: "Alibaba Bailian (Model Studio) OpenAI-compatible defaults.",
  baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
  docsUrl: "https://docs.bailian.console.aliyun.com/zh/model-studio/models",
  models: [
    createModel(
      "qwen-max",
      "Qwen Max",
      false,
      ["toolcalling", "structuredOutput"],
      ["messages", "responses"],
      32768,
      8192,
      true,
      false,
    ),
    createModel(
      "qwen-plus",
      "Qwen Plus",
      false,
      ["toolcalling", "structuredOutput"],
      ["messages", "responses"],
      131072,
      8192,
      true,
      true,
    ),
    createModel(
      "qwen-flash",
      "Qwen Flash",
      false,
      ["toolcalling"],
      ["messages", "responses"],
      1000000,
      8192,
      true,
      true,
    ),
    createModel(
      "qwen-turbo",
      "Qwen Turbo",
      false,
      ["toolcalling"],
      ["messages", "responses"],
      1000000,
      8192,
      true,
      false,
    ),
    createModel(
      "qwen-long",
      "Qwen Long",
      false,
      ["toolcalling"],
      ["messages", "responses"],
      10000000,
      8192,
      false,
      false,
    ),
    createModel(
      "qwen-vl-max",
      "Qwen VL Max",
      false,
      ["toolcalling", "vision"],
      ["messages", "responses"],
      131072,
      8192,
      true,
      false,
    ),
    createModel(
      "qwen-vl-plus",
      "Qwen VL Plus",
      false,
      ["toolcalling", "vision"],
      ["messages", "responses"],
      131072,
      8192,
      true,
      false,
    ),
  ],
}
