import crypto from "node:crypto"
import { ipcMain } from "electron"
import { applyMigrations, openDatabase } from "@electron/database/db-core"
import { ensureWorkspace } from "@electron/others/workspace"

const defaultConfig = JSON.stringify({ instructions: "You are a helpful agent.", providerId: "provider-openai", modelId: "gpt-5", maxSteps: 100, workflowIds: [], skillIds: [], toolsetIds: [], documentIds: [] })
const selectAgent = `SELECT id, title, kind, summary, updated_at as updatedAt FROM agents`
export function registerAgentIpc() {
  ipcMain.handle("agents:list", async () => { const db = await database(); return db.prepare(`${selectAgent} ORDER BY updated_at DESC`).all() })
  ipcMain.handle("agents:get", async (_event, id: string) => { const db = await database(); const agent = db.prepare(`${selectAgent} WHERE id = ?`).get(id) ?? null; if (!agent) return { agent: null, versions: [] }; if (!(db.prepare(`SELECT COUNT(*) as count FROM agent_versions WHERE agent_id = ?`).get(id) as { count: number }).count) db.prepare(`INSERT INTO agent_versions (id, agent_id, major, minor, is_release, config_json, created_at) VALUES (?, ?, 1, 0, 0, ?, ?)`).run(crypto.randomUUID(), id, defaultConfig, Date.now()); return { agent, versions: db.prepare(`SELECT id, major, minor, is_release as isRelease, created_at as createdAt, config_json as configJson FROM agent_versions WHERE agent_id = ? ORDER BY major DESC, minor DESC, created_at DESC`).all(id) } })
  ipcMain.handle("agents:create", async () => { const db = await database(); const id = crypto.randomUUID(); const versionId = crypto.randomUUID(); const now = Date.now(); db.prepare(`INSERT INTO agents (id, title, kind, summary, updated_at) VALUES (?, ?, ?, ?, ?)`).run(id, "New agent", "custom", "", now); db.prepare(`INSERT INTO agent_versions (id, agent_id, major, minor, is_release, config_json, created_at) VALUES (?, ?, 1, 0, 0, ?, ?)`).run(versionId, id, defaultConfig, now); return getAgent(db, id, versionId) })
  ipcMain.handle("agents:save", async (_event, payload: { id: string; title: string; kind: string; summary: string; configJson: string; selectedVersionId?: string; publish?: boolean }) => { const db = await database(); const now = Date.now(); db.prepare(`INSERT INTO agents (id, title, kind, summary, updated_at) VALUES (?, ?, ?, ?, ?) ON CONFLICT(id) DO UPDATE SET title = excluded.title, kind = excluded.kind, summary = excluded.summary, updated_at = excluded.updated_at`).run(payload.id, payload.title, payload.kind, payload.summary, now); const draft = payload.selectedVersionId ? db.prepare(`SELECT id, is_release as isRelease FROM agent_versions WHERE agent_id = ? AND id = ?`).get(payload.id, payload.selectedVersionId) as { id: string; isRelease: number } | undefined : undefined; const selected = draft && !draft.isRelease ? draft.id : undefined; if (!payload.publish && selected) db.prepare(`UPDATE agent_versions SET config_json = ?, created_at = ? WHERE id = ?`).run(payload.configJson, now, selected); else { const latest = db.prepare(`SELECT major, minor, is_release as isRelease FROM agent_versions WHERE agent_id = ? ORDER BY major DESC, minor DESC, created_at DESC LIMIT 1`).get(payload.id) as { major: number; minor: number; isRelease: number } | undefined; db.prepare(`INSERT INTO agent_versions (id, agent_id, major, minor, is_release, config_json, created_at) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(crypto.randomUUID(), payload.id, !latest ? 1 : latest.isRelease ? latest.major + 1 : latest.major, !latest || latest.isRelease ? 0 : latest.minor + 1, payload.publish ? 1 : 0, payload.configJson, now) } return getAgent(db, payload.id) })
  ipcMain.handle("agents:delete", async (_event, id: string) => { const db = await database(); db.prepare(`DELETE FROM agent_versions WHERE agent_id = ?`).run(id); db.prepare(`DELETE FROM agents WHERE id = ?`).run(id); return { success: true } })
  ipcMain.handle("agents:getSettings", async () => getSetting("agent_settings"))
  ipcMain.handle("agents:saveSettings", async (_event, value: unknown) => { const db = await database(); db.prepare(`INSERT INTO app_meta (key, value) VALUES ('agent_settings', ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value`).run(JSON.stringify(value)); return value })
}
function getAgent(db: ReturnType<typeof openDatabase>, id: string, selectedVersionId?: string) { return { agent: db.prepare(`${selectAgent} WHERE id = ?`).get(id), versions: db.prepare(`SELECT id, major, minor, is_release as isRelease, created_at as createdAt, config_json as configJson FROM agent_versions WHERE agent_id = ? ORDER BY major DESC, minor DESC, created_at DESC`).all(id), ...(selectedVersionId ? { selectedVersionId } : {}) } }
async function getSetting(key: string) { const db = await database(); return (db.prepare(`SELECT value FROM app_meta WHERE key = ?`).get(key) as { value?: string } | undefined)?.value ?? null }
async function database() { await ensureWorkspace(); const db = openDatabase(); applyMigrations(db); return db }
