import fs from "node:fs/promises"
import path from "node:path"
import { ipcMain } from "electron"
import { appState } from "@electron/others/app-state"
import { ensureFileSizeWithinLimit, MAX_TOOL_FILE_BYTES, MAX_TOOL_WRITE_BYTES } from "@electron/others/tool-guardrails"
import { ensureWorkspace } from "@electron/others/workspace"
import { resolveWorkspaceTarget, enforceRelativePathPolicy } from "@electron/ipc/tools/tools-policy"
export function registerToolFilesystemIpc() {
  ipcMain.handle("tools:listFiles", async (_event, relativePath?: string) => { await ensureWorkspace(); const target = resolveWorkspaceTarget(relativePath); enforceRelativePathPolicy(relativePath, target); return (await fs.readdir(target, { withFileTypes: true })).map((entry) => ({ name: entry.name, path: path.relative(resolveWorkspaceTarget(), path.join(target, entry.name)).replace(/\\/g, "/"), type: entry.isDirectory() ? "directory" : "file" })) })
  ipcMain.handle("tools:readFile", async (_event, relativePath: string) => { await ensureWorkspace(); const target = resolveWorkspaceTarget(relativePath); enforceRelativePathPolicy(relativePath, target); const stats = await fs.stat(target); ensureFileSizeWithinLimit(stats.size, `File '${relativePath}'`, MAX_TOOL_FILE_BYTES); return { path: path.relative(resolveWorkspaceTarget(), target).replace(/\\/g, "/"), content: await fs.readFile(target, "utf8") } })
  ipcMain.handle("tools:writeFile", async (_event, payload: { path: string; content: string }) => { await ensureWorkspace(); const target = resolveWorkspaceTarget(payload.path); enforceRelativePathPolicy(payload.path, target); ensureFileSizeWithinLimit(Buffer.byteLength(payload.content, "utf8"), `Write payload for '${payload.path}'`, MAX_TOOL_WRITE_BYTES); await fs.mkdir(path.dirname(target), { recursive: true }); await fs.writeFile(target, payload.content, "utf8"); return { ok: true, path: path.relative(resolveWorkspaceTarget(), target).replace(/\\/g, "/") } })
  ipcMain.handle("tools:saveFile", async (_event, payload: { defaultName: string; filters?: Array<{ name: string; extensions: string[] }>; dataBase64: string }) => { const browserWindow = appState.mainWindow ?? undefined; const { dialog, app } = await import("electron"); const result = await dialog.showSaveDialog(browserWindow, { defaultPath: path.join(app.getPath("documents"), payload.defaultName), filters: payload.filters }); if (result.canceled || !result.filePath) return { ok: true, canceled: true, path: null }; await fs.writeFile(result.filePath, Buffer.from(payload.dataBase64, "base64")); return { ok: true, canceled: false, path: result.filePath } })
}
