import path from "node:path"
import { applyMigrations, openDatabase } from "@electron/database/db-core"
import { ensureWorkspace } from "@electron/others/workspace"
import { getWorkspacePath } from "@electron/others/paths"

type ToolPreferenceSettings = { fileAccessPolicy?: "allowlist" | "denylist"; fileAccessDirectories?: string[]; commandAllowlist?: string[]; commandBlacklist?: string[]; globalEnvironmentVariables?: Array<{ key?: string; value?: string }> }
export function readToolPreferences(): ToolPreferenceSettings { const database = openDatabase(); applyMigrations(database); const row = database.prepare("SELECT value FROM app_meta WHERE key = 'preference_settings'").get() as { value?: string } | undefined; try { return row?.value ? JSON.parse(row.value) as ToolPreferenceSettings : {} } catch { return {} } }
export function normalizeRuleList(value: unknown) { return Array.isArray(value) ? value.filter((item): item is string => typeof item === "string").map((item) => item.trim().toLowerCase()).filter(Boolean) : [] }
export function resolveWorkspaceTarget(relativePath = ".") { const root = path.resolve(getWorkspacePath()); const target = path.resolve(root, relativePath); if (target !== root && !target.startsWith(`${root}${path.sep}`)) throw new Error("Path must stay within the workspace root."); return target }
export function enforceRelativePathPolicy(relativePath: string | undefined, target: string) { const preferences = readToolPreferences(); const relative = path.relative(path.resolve(getWorkspacePath()), target).replace(/\\/g, "/").toLowerCase(); const rules = normalizeRuleList(preferences.fileAccessDirectories); if (!rules.length) return; const matches = rules.some((rule) => { const normalized = rule.replace(/^\.\//, "").replace(/\/$/, ""); return normalized === "." ? relative === "" : relative === normalized || relative.startsWith(`${normalized}/`) }); if (preferences.fileAccessPolicy === "allowlist" && !matches) throw new Error(`Access to '${relativePath ?? "."}' is outside the allowed directories.`); if (preferences.fileAccessPolicy !== "allowlist" && matches) throw new Error(`Access to '${relativePath ?? "."}' is blocked by the file access policy.`) }
export function enforceCommandPolicy(command: string, executableName: string) { const preferences = readToolPreferences(); const normalized = command.trim().toLowerCase(); const allowlist = normalizeRuleList(preferences.commandAllowlist); const blocked = normalizeRuleList(preferences.commandBlacklist).find((entry) => normalized.includes(entry)); if (allowlist.length && !allowlist.includes(executableName.toLowerCase())) throw new Error(`Command blocked by allowlist: ${executableName}`); if (blocked) throw new Error(`Command blocked by preferences: ${blocked}`) }
export async function ensureToolWorkspace() { await ensureWorkspace() }
