import crypto from "node:crypto"
import { ipcMain } from "electron"
import { applyMigrations, openDatabase } from "@electron/database/db-core"
import { parseAppendAssistantPayload, parseAppendUserPayload, parseChatSettingsSavePayload, parseStoredChatMessageParts, parseStoredChatSettingsStore, parseUpdateMessagePartsPayload, serializeChatMessageParts, serializeChatSettingsStore } from "@electron/others/chat-schemas"
import type { ChatRuntimeSettingsPayload } from "@electron/types"
import { setProxySettings } from "@electron/others/proxy"
import { ensureWorkspace } from "@electron/others/workspace"

const selectChat = `SELECT id, title, chatbot_id as chatbotId, summary, source_type as sourceType, source_ref as sourceRef, updated_at as updatedAt FROM chats`
export function registerChatIpc() {
  ipcMain.handle("chats:list", async () => { const database = await getDatabase(); return database.prepare(`${selectChat} WHERE EXISTS (SELECT 1 FROM chat_messages WHERE chat_messages.chat_id = chats.id) ORDER BY updated_at DESC`).all() })
  ipcMain.handle("chats:get", async (_event, id: string) => getChat(id))
  ipcMain.handle("chats:create", async () => { const database = await getDatabase(); const id = crypto.randomUUID(); const now = Date.now(); database.prepare(`INSERT INTO chats (id, title, chatbot_id, summary, source_type, source_ref, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(id, "New chat", "assistant-main", "", "manual", null, now); return getChat(id) })
  ipcMain.handle("chats:ensure", async (_event, payload: { chatId: string; title: string; chatbotId: string; summary?: string; sourceType?: "manual" | "channel"; sourceRef?: string | null }) => { const database = await getDatabase(); const existing = database.prepare(`${selectChat} WHERE id = ?`).get(payload.chatId) as { summary?: string; sourceType?: string; sourceRef?: string } | undefined; const values = [payload.title, payload.chatbotId, payload.summary ?? existing?.summary ?? "", payload.sourceType ?? existing?.sourceType ?? "manual", payload.sourceRef ?? existing?.sourceRef ?? null, Date.now(), payload.chatId]; if (existing) database.prepare(`UPDATE chats SET title = ?, chatbot_id = ?, summary = ?, source_type = ?, source_ref = ?, updated_at = ? WHERE id = ?`).run(...values); else database.prepare(`INSERT INTO chats (id, title, chatbot_id, summary, source_type, source_ref, updated_at) VALUES (?, ?, ?, ?, ?, ?, ?)`).run(payload.chatId, ...values.slice(0, -1)); return getChat(payload.chatId) })
  ipcMain.handle("chats:delete", async (_event, id: string) => { const database = await getDatabase(); database.prepare(`DELETE FROM chat_messages WHERE chat_id = ?`).run(id); return Number(database.prepare(`DELETE FROM chats WHERE id = ?`).run(id).changes ?? 0) > 0 })
  ipcMain.handle("chats:appendUser", async (_event, value: unknown) => appendMessage(parseAppendUserPayload(value), "user"))
  ipcMain.handle("chats:appendAssistant", async (_event, value: unknown) => appendMessage(parseAppendAssistantPayload(value), "assistant"))
  ipcMain.handle("chats:updateMessageParts", async (_event, value: unknown) => { const payload = parseUpdateMessagePartsPayload(value); const database = await getDatabase(); if (!database.prepare(`SELECT id FROM chats WHERE id = ?`).get(payload.chatId)) return null; const result = database.prepare(`UPDATE chat_messages SET parts_json = ? WHERE id = ? AND chat_id = ?`).run(serializeChatMessageParts(payload.parts), payload.messageId, payload.chatId); if (!result.changes) throw new Error(`Message ${payload.messageId} was not found in chat ${payload.chatId}.`); database.prepare(`UPDATE chats SET updated_at = ? WHERE id = ?`).run(Date.now(), payload.chatId); return getChat(payload.chatId) })
  ipcMain.handle("chats:getSettings", async () => { const database = await getDatabase(); const row = database.prepare(`SELECT value FROM app_meta WHERE key = 'chat_runtime_settings'`).get() as { value?: string } | undefined; const parsed = parseStoredChatSettingsStore(row?.value ?? null); if (parsed?.store.defaultRuntime?.proxy) setProxySettings(parsed.store.defaultRuntime.proxy); return parsed ? serializeChatSettingsStore(parsed.store) : row?.value ?? null })
  ipcMain.handle("chats:saveSettings", async (_event, value: ChatRuntimeSettingsPayload | { defaultRuntime?: ChatRuntimeSettingsPayload; chats?: Record<string, { runtime?: ChatRuntimeSettingsPayload; selectedAgentId?: string }> }) => { const parsed = parseChatSettingsSavePayload(value); const database = await getDatabase(); const store = "version" in parsed ? parsed.store : parsed; database.prepare(`INSERT INTO app_meta (key, value) VALUES ('chat_runtime_settings', ?) ON CONFLICT(key) DO UPDATE SET value = excluded.value`).run(serializeChatSettingsStore(store)); if ("proxy" in parsed ? parsed.proxy : store.defaultRuntime?.proxy) setProxySettings(("proxy" in parsed ? parsed.proxy : store.defaultRuntime?.proxy)!); return "version" in parsed ? parsed : { version: 1, store } })
}
async function appendMessage(payload: { chatId: string; content: string; parts?: unknown[] }, role: string) { const database = await getDatabase(); const chat = database.prepare(`SELECT id, title FROM chats WHERE id = ?`).get(payload.chatId) as { id: string; title: string } | undefined; if (!chat) return null; const content = payload.content.trim(); const now = Date.now(); database.prepare(`INSERT INTO chat_messages (id, chat_id, role, content, parts_json, created_at) VALUES (?, ?, ?, ?, ?, ?)`).run(crypto.randomUUID(), payload.chatId, role, content, serializeChatMessageParts(payload.parts ?? []), now); if (role === "user") database.prepare(`UPDATE chats SET title = ?, summary = ?, updated_at = ? WHERE id = ?`).run(chat.title === "New chat" ? content.slice(0, 18) || "Untitled chat" : chat.title, content, now, payload.chatId); else database.prepare(`UPDATE chats SET updated_at = ? WHERE id = ?`).run(now, payload.chatId); return getChat(payload.chatId) }
async function getChat(id: string) { const database = await getDatabase(); return { chat: database.prepare(`${selectChat} WHERE id = ?`).get(id) ?? null, messages: (database.prepare(`SELECT id, role, content, parts_json as partsJson, created_at as createdAt FROM chat_messages WHERE chat_id = ? ORDER BY created_at ASC`).all(id) as Array<{ partsJson: string }>).map((message) => ({ ...message, parts: parseStoredChatMessageParts(message.partsJson) })) } }
async function getDatabase() { await ensureWorkspace(); const database = openDatabase(); applyMigrations(database); return database }
