import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    'workbench-map',
    'module-hub',
    'deep-dive-hub',
    'user-deep-hub',
    'user-deep-chat',
    'user-deep-documents',
    'user-deep-pipeline',
    'user-deep-models',
    'user-deep-agents',
    'user-deep-skills',
    'user-deep-timer',
    'user-deep-channels',
    'user-deep-mcp',
    'user-deep-settings',
    'technical-deep-hub',
    'technical-deep-chat',
    'technical-deep-documents',
    'technical-deep-pipeline',
    'technical-deep-models',
    'technical-deep-agents',
    'technical-deep-skills',
    'technical-deep-timer',
    'technical-deep-channels',
    'technical-deep-mcp',
    'technical-deep-settings',
    'module-chat',
    'module-documents',
    'module-pipeline',
    'module-models',
    'module-agents',
    'module-skills',
    'module-timer',
    'module-channels',
    'module-mcp',
    'module-settings',
    'slash-commands',
    'docs-library',
    'downloads',
  ],
};

export default sidebars;
